# Generated by Django 2.2.13 on 2020-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200624_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='icon/sugar.png', upload_to='icon/'),
        ),
    ]
