# Generated by Django 2.2.13 on 2020-06-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20200625_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='thread',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='slack.ChatMessage'),
            preserve_default=False,
        ),
    ]
