# Generated by Django 2.2.13 on 2020-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_comments_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='thread',
            new_name='chatmessage',
        ),
    ]
