# Generated by Django 2.2.13 on 2020-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_auto_20200626_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='chatlog',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
