# Generated by Django 2.2.13 on 2020-07-03 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slack', '0018_comments_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecredMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
