# Generated by Django 2.2.14 on 2020-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secredmessage',
            name='yourname',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
    ]
