# Generated by Django 2.2.13 on 2020-06-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_chatmessage_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
