# Generated by Django 2.2.14 on 2020-07-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20200706_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='images'),
        ),
    ]
