# Generated by Django 2.2.14 on 2020-07-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20200707_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
