# Generated by Django 2.2.14 on 2020-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0005_auto_20200707_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(default=10, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secredmessage',
            name='text',
            field=models.CharField(default=10, max_length=1000),
            preserve_default=False,
        ),
    ]
