# Generated by Django 2.2.14 on 2020-07-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_auto_20200707_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secredmessage',
            options={'ordering': ['created_date']},
        ),
    ]
