# Generated by Django 2.2.14 on 2020-07-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_auto_20200708_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secredmessage',
            options={},
        ),
    ]
