# Generated by Django 2.2.13 on 2020-06-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0008_auto_20200627_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='chatmessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='slack.ChatMessage', unique=True),
        ),
    ]
