# Generated by Django 2.2.13 on 2020-06-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_auto_20200627_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='chatmessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='slack.ChatMessage'),
        ),
    ]
