# Generated by Django 2.2.13 on 2020-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0013_auto_20200628_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='icon',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='icon',
            field=models.URLField(),
        ),
    ]
