# Generated by Django 2.2.13 on 2020-06-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0015_auto_20200628_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='favorite',
        ),
    ]
