# Generated by Django 2.2.13 on 2020-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0016_remove_chatmessage_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
