# Generated by Django 2.2.13 on 2020-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200627_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images.png', null=True, upload_to='icon/'),
        ),
    ]
